server:
  port: 9522

spring:
  datasource:
    url: ${ELEC_APP_DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true


  data:
    mongodb:
      uri: ${MONGO_DB_URL}

springdoc:
  swagger-ui:
    path: ${SWAGGER_URL}



